config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root "projects#index"
  get '/projects/new', to: "projects#new"
  get '/projects/edit', to: "projects#edit"
  get '/projects/:id', to: "projects#show" 
  get '/students/sign_in(.:format)', to: "devise/sessions#new"

  resources :projects
  # See https://stackoverflow.com/a/5911863 for how the routing below works. (it is for the about me page)
  get '/:page' =>   "static#show"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json, see: before_action method. 
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def show
        render params[:page]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Portfolio</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About Me</a>
        </li>
        <li class="nav-item">
          <% if student_signed_in? %>
            <%= link_to 'Log out', destroy_student_session_path, method: :delete ,  class: "nav-link" %>
          <% else %>
            <%= link_to 'Log in', new_student_session_path,  class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if !student_signed_in? %>
            <%= link_to 'Sign up', new_student_registration_path, class: "nav-link" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

  <body>
    <%= yield %>
  </body>

</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<style>
.btn {
  color: #ffffff;
}
</style>

<p id="notice"><%= notice %></p>

<h1 class="text-center">Charlie Penvari </h1>
<h2 class="text-center">Projects Portfolio </h2>


<tbody>
  <% @projects.each do |project| %>   
    <div class="card text-center">
      <div class="card-body">
        <h5 class="card-title"><%= project.title %> </h5>
        <p class="card-text"><%= project.description %></p>
          <%= link_to 'Show', project, class: "btn btn-primary" %>
          <%if student_signed_in? %>
            <%= link_to 'Edit', edit_project_path(project), class: "btn btn-primary"%>
            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <% end %>
      </div>
    </div>

  <% end %>
</tbody>

<br>
<%if student_signed_in? %>
  <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4">
  <p class="h3">Title: <%= @project.title %> </p>

</h1>

<p>
  <p class="h3">Description:</p>
  <%= @project.description %>
</p>
<br>
<p class ="card-text" > <%= link_to 'Back', projects_path %> </p>
<%if student_signed_in? %>
  <%= link_to 'Edit', edit_project_path(@project) %> 
<%end %>